name: Security

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  node-audit:
    uses: netresearch/.github/.github/workflows/node-audit.yml@719efa1363a09402610a5e515f668eff54ec4e23 # main
    with:
      package-manager: npm
      audit-level: high

  gitleaks:
    uses: netresearch/.github/.github/workflows/gitleaks.yml@719efa1363a09402610a5e515f668eff54ec4e23 # main
    secrets: inherit
